mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.leiyonglin.pojo

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://118.24.137.85:3306/graduatetask
    username: cinema
    password: cinema@Centos7
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource